// <auto-generated />
using System;
using Cold.Contracts.Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cold.Contracts.Core.DAL.Migrations
{
    [DbContext(typeof(ContractsDbContext))]
    [Migration("20251110115730_AddContractAmendmentTable")]
    partial class AddContractAmendmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contracts")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cold.Contracts.Core.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("ContractStatusId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("ContractStatusId");

                    b.ToTable("Contracts", "contracts");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractAmendment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AmendmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AmendmentNumber")
                        .IsUnique();

                    b.HasIndex("ContractId");

                    b.ToTable("ContractAmendments", "contracts");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractProduct", b =>
                {
                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("ContractId", "ProductId");

                    b.ToTable("ContractProducts", "contracts");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ContractStatuses", "contracts");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Description = "Contract is in draft state",
                            Name = "Draft"
                        },
                        new
                        {
                            Id = (short)2,
                            Description = "Contract is pending farmer acceptance",
                            Name = "PendingAcceptance"
                        },
                        new
                        {
                            Id = (short)3,
                            Description = "Contract is active and accepted",
                            Name = "Active"
                        },
                        new
                        {
                            Id = (short)4,
                            Description = "Contract was rejected by farmer",
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = (short)5,
                            Description = "Contract has expired",
                            Name = "Expired"
                        },
                        new
                        {
                            Id = (short)6,
                            Description = "Contract has been completed",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = (short)7,
                            Description = "Contract was terminated early",
                            Name = "Terminated"
                        });
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.Contract", b =>
                {
                    b.HasOne("Cold.Contracts.Core.Entities.ContractStatus", "ContractStatus")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContractStatus");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractAmendment", b =>
                {
                    b.HasOne("Cold.Contracts.Core.Entities.Contract", "Contract")
                        .WithMany("Amendments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractProduct", b =>
                {
                    b.HasOne("Cold.Contracts.Core.Entities.Contract", "Contract")
                        .WithMany("ContractProducts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.Contract", b =>
                {
                    b.Navigation("Amendments");

                    b.Navigation("ContractProducts");
                });

            modelBuilder.Entity("Cold.Contracts.Core.Entities.ContractStatus", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
