@url = http://localhost:5136
@deliveryId = a6d2dbc7-d335-4fbe-b46b-1c69b3063e7c
@deliveryNumber = DEL-002
@supplierId = 00000000-0000-0000-0000-000000000001
@productId1 = 019a6ad2-1779-7ad9-b238-b43c01d5cf03
@productId2 = 019a6a8f-3755-71e0-8686-08a671cc4425

###
GET {{url}}/ping

###
GET {{url}}/deliveries/{{deliveryId}}

###
GET {{url}}/deliveries/by-number/{{deliveryNumber}}

###
GET {{url}}/deliveries

###
GET {{url}}/deliveries/by-supplier/{{supplierId}}

###
GET {{url}}/deliveries/uninvoiced

###
GET {{url}}/deliveries/uninvoiced/by-supplier/{{supplierId}}

###
POST {{url}}/deliveries
Content-Type: application/json

{
    "deliveryNumber": "{{deliveryNumber}}",
    "supplierId": "{{supplierId}}",
    "deliveryDate": "2025-11-11T10:00:00Z",
    "notes": "Delivery notes 2",
    "products": [
        {
            "productId": "{{productId1}}",
            "classType": "I",
            "quantity": 17.10
        },
        {
            "productId": "{{productId2}}",
            "classType": "III",
            "quantity": 233.99
        }
    ]
}

###
PUT {{url}}/deliveries/{{deliveryId}}
Content-Type: application/json

{
    "deliveryNumber": "{{deliveryNumber}}",
    "supplierId": "{{supplierId}}",
    "deliveryDate": "2025-11-11T12:00:00Z",
    "notes": "Updated delivery notes",
    "products": [
        {
            "productId": "{{productId1}}",
            "classType": "I",
            "quantity": 120.0
        },
        {
            "productId": "{{productId2}}",
            "classType": "II",
            "quantity": 60.0
        }
    ]
}

###
POST {{url}}/deliveries/{{deliveryId}}/mark-invoiced
