// <auto-generated />
using System;
using Cold.Deliveries.Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cold.Deliveries.Core.DAL.Migrations
{
    [DbContext(typeof(DeliveriesDbContext))]
    [Migration("20251111142717_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deliveries")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsInvoiced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryNumber")
                        .IsUnique();

                    b.ToTable("Deliveries", "deliveries");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.DeliveryPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("DeliveryPhotos", "deliveries");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.DeliveryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.ToTable("DeliveryProducts", "deliveries");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualPickupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledPickupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<short>("TransportStatusId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("TransportStatusId");

                    b.ToTable("TransportRequests", "deliveries");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.TransportStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TransportStatuses", "deliveries");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DisplayName = "Do realizacji",
                            Name = "ToRealize"
                        },
                        new
                        {
                            Id = (short)2,
                            DisplayName = "W drodze do dostawcy",
                            Name = "OnWayToSupplier"
                        },
                        new
                        {
                            Id = (short)3,
                            DisplayName = "U dostawcy",
                            Name = "AtSupplier"
                        },
                        new
                        {
                            Id = (short)4,
                            DisplayName = "W drodze do chłodni",
                            Name = "OnWayToColdStorage"
                        },
                        new
                        {
                            Id = (short)5,
                            DisplayName = "W chłodni",
                            Name = "InColdStorage"
                        },
                        new
                        {
                            Id = (short)6,
                            DisplayName = "Anulowano",
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.DeliveryPhoto", b =>
                {
                    b.HasOne("Cold.Deliveries.Core.Entities.Delivery", "Delivery")
                        .WithMany("Photos")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.DeliveryProduct", b =>
                {
                    b.HasOne("Cold.Deliveries.Core.Entities.Delivery", "Delivery")
                        .WithMany("DeliveryProducts")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.TransportRequest", b =>
                {
                    b.HasOne("Cold.Deliveries.Core.Entities.Delivery", "Delivery")
                        .WithMany("TransportRequests")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cold.Deliveries.Core.Entities.TransportStatus", "TransportStatus")
                        .WithMany("TransportRequests")
                        .HasForeignKey("TransportStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("TransportStatus");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.Delivery", b =>
                {
                    b.Navigation("DeliveryProducts");

                    b.Navigation("Photos");

                    b.Navigation("TransportRequests");
                });

            modelBuilder.Entity("Cold.Deliveries.Core.Entities.TransportStatus", b =>
                {
                    b.Navigation("TransportRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
